name: mflow_projects
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=21.0.1
  - pip:
    - numpy=1.2.*
    - torch=1.7.*
    - pillow=7.2.*
    - mlflow=1.12.*
    - wget=3.*